//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.11.05 at 03:49:52 PM ICT 
//


package model.entity.attendance;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="Attendance"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="StudentId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="ScheduleId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="GroupName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="CourseName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="Present" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "attendance"
})
@XmlRootElement(name = "Attendances")
public class Attendances {

    @XmlElement(name = "Attendance")
    protected List<Attendances.Attendance> attendance;

    /**
     * Gets the value of the attendance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attendance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttendance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Attendances.Attendance }
     * 
     * 
     */
    public List<Attendances.Attendance> getAttendance() {
        if (attendance == null) {
            attendance = new ArrayList<Attendances.Attendance>();
        }
        return this.attendance;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="StudentId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="ScheduleId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="GroupName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="CourseName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="Present" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
    	"Attendance_Id",
        "studentId",
        "Attendance_Slot",
        "Attendance_Lecture",
        "Attendance_Date_Id",
        "Attendance_Status",
        "Attendance_GroupName",
        "Attendance_Course"
    })
    public static class Attendance {
    	@XmlElement(name = "Attendance_Id")
        protected String Attendance_Id;
        @XmlElement(name = "studentId")
        protected String studentId;
        @XmlElement(name = "Attendance_Slot")
        protected String Attendance_Slot;
        @XmlElement(name = "Attendance_Lecture")
        protected String Attendance_Lecture;
        @XmlElement(name = "Attendance_Date_Id")
        protected String Attendance_Date_Id;
        @XmlElement(name = "Attendance_Status")
        protected int Attendance_Status;
        @XmlElement(name = "Attendance_GroupName")
        protected String Attendance_GroupName;
        @XmlElement(name = "Attendance_Course")
        protected String Attendance_Course;
        
		public String getAttendance_Id() {
			return Attendance_Id;
		}
		public void setAttendance_Id(String attendance_Id) {
			Attendance_Id = attendance_Id;
		}
		public String getStudentId() {
			return studentId;
		}
		public void setStudentId(String studentId) {
			this.studentId = studentId;
		}
		public String getAttendance_Slot() {
			return Attendance_Slot;
		}
		public void setAttendance_Slot(String attendance_Slot) {
			Attendance_Slot = attendance_Slot;
		}
		public String getAttendance_Lecture() {
			return Attendance_Lecture;
		}
		public void setAttendance_Lecture(String attendance_Lectures) {
			Attendance_Lecture = attendance_Lectures;
		}
		public String getAttendance_Date_Id() {
			return Attendance_Date_Id;
		}
		public void setAttendance_Date_Id(String attendance_Date_Ids) {
			Attendance_Date_Id = attendance_Date_Ids;
		}
		public int getAttendance_Status() {
			return Attendance_Status;
		}
		public void setAttendance_Status(int attendance_Status) {
			Attendance_Status = attendance_Status;
		}
		public String getAttendance_GroupName() {
			return Attendance_GroupName;
		}
		public void setAttendance_GroupName(String attendance_GroupName) {
			Attendance_GroupName = attendance_GroupName;
		}
		public String getAttendance_Course() {
			return Attendance_Course;
		}
		public void setAttendance_Course(String attendance_Course) {
			Attendance_Course = attendance_Course;
		}		
		
    }

}
